/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct MonthDetail {
    #[serde(rename = "month")]
    pub month: String,
    #[serde(rename = "note")]
    pub note: String,
    /// The total amount in transactions categorized to 'Inflow: To be Budgeted' in the month
    #[serde(rename = "income")]
    pub income: i64,
    /// The total amount budgeted in the month
    #[serde(rename = "budgeted")]
    pub budgeted: i64,
    /// The total amount in transactions in the month, excluding those categorized to 'Inflow: To be Budgeted'
    #[serde(rename = "activity")]
    pub activity: i64,
    /// The available amount for 'To be Budgeted'
    #[serde(rename = "to_be_budgeted")]
    pub to_be_budgeted: i64,
    /// The Age of Money as of the month
    #[serde(rename = "age_of_money")]
    pub age_of_money: i32,
    /// Whether or not the month has been deleted.  Deleted months will only be included in delta requests.
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// The budget month categories.  Amounts (budgeted, activity, balance, etc.) are specific to the {month} parameter specified.
    #[serde(rename = "categories")]
    pub categories: Vec<::models::Category>,
}

impl MonthDetail {
    pub fn new(month: String, note: String, income: i64, budgeted: i64, activity: i64, to_be_budgeted: i64, age_of_money: i32, deleted: bool, categories: Vec<::models::Category>) -> MonthDetail {
        MonthDetail {
            month: month,
            note: note,
            income: income,
            budgeted: budgeted,
            activity: activity,
            to_be_budgeted: to_be_budgeted,
            age_of_money: age_of_money,
            deleted: deleted,
            categories: categories,
        }
    }
}


