/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;

use super::{Error, configuration};

pub struct DeprecatedApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl DeprecatedApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> DeprecatedApiClient {
        DeprecatedApiClient {
            configuration: configuration,
        }
    }
}

pub trait DeprecatedApi {
    fn bulk_create_transactions(&self, budget_id: &str, transactions: crate::models::BulkTransactions) -> Result<crate::models::BulkResponse, Error>;
}

impl DeprecatedApi for DeprecatedApiClient {
    fn bulk_create_transactions(&self, budget_id: &str, transactions: crate::models::BulkTransactions) -> Result<crate::models::BulkResponse, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/budgets/{budget_id}/transactions/bulk", configuration.base_path, budget_id=crate::apis::urlencode(budget_id));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&transactions);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
