/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PayeeLocation {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "payee_id")]
    pub payee_id: String,
    #[serde(rename = "latitude")]
    pub latitude: String,
    #[serde(rename = "longitude")]
    pub longitude: String,
    /// Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl PayeeLocation {
    pub fn new(id: String, payee_id: String, latitude: String, longitude: String, deleted: bool) -> PayeeLocation {
        PayeeLocation {
            id: id,
            payee_id: payee_id,
            latitude: latitude,
            longitude: longitude,
            deleted: deleted,
        }
    }
}


