/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct ScheduledTransactionDetailAllOf {
    #[serde(rename = "account_name")]
    pub account_name: String,
    #[serde(rename = "payee_name")]
    pub payee_name: String,
    #[serde(rename = "category_name")]
    pub category_name: String,
    /// If a split scheduled transaction, the subtransactions.
    #[serde(rename = "subtransactions")]
    pub subtransactions: Vec<::models::ScheduledSubTransaction>,
}

impl ScheduledTransactionDetailAllOf {
    pub fn new(account_name: String, payee_name: String, category_name: String, subtransactions: Vec<::models::ScheduledSubTransaction>) -> ScheduledTransactionDetailAllOf {
        ScheduledTransactionDetailAllOf {
            account_name: account_name,
            payee_name: payee_name,
            category_name: category_name,
            subtransactions: subtransactions,
        }
    }
}


