/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.72.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledTransactionSummary {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The first date for which the Scheduled Transaction was scheduled.
    #[serde(rename = "date_first")]
    pub date_first: String,
    /// The next date for which the Scheduled Transaction is scheduled.
    #[serde(rename = "date_next")]
    pub date_next: String,
    #[serde(rename = "frequency")]
    pub frequency: Frequency,
    /// The scheduled transaction amount in milliunits format
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "memo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memo: Option<Option<String>>,
    #[serde(rename = "flag_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag_color: Option<Option<models::TransactionFlagColor>>,
    /// The customized name of a transaction flag
    #[serde(rename = "flag_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag_name: Option<Option<String>>,
    #[serde(rename = "account_id")]
    pub account_id: uuid::Uuid,
    #[serde(rename = "payee_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "category_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<Option<uuid::Uuid>>,
    /// If a transfer, the account_id which the scheduled transaction transfers to
    #[serde(rename = "transfer_account_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transfer_account_id: Option<Option<uuid::Uuid>>,
    /// Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl ScheduledTransactionSummary {
    pub fn new(id: uuid::Uuid, date_first: String, date_next: String, frequency: Frequency, amount: i64, account_id: uuid::Uuid, deleted: bool) -> ScheduledTransactionSummary {
        ScheduledTransactionSummary {
            id,
            date_first,
            date_next,
            frequency,
            amount,
            memo: None,
            flag_color: None,
            flag_name: None,
            account_id,
            payee_id: None,
            category_id: None,
            transfer_account_id: None,
            deleted,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Frequency {
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "everyOtherWeek")]
    EveryOtherWeek,
    #[serde(rename = "twiceAMonth")]
    TwiceAMonth,
    #[serde(rename = "every4Weeks")]
    Every4Weeks,
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "everyOtherMonth")]
    EveryOtherMonth,
    #[serde(rename = "every3Months")]
    Every3Months,
    #[serde(rename = "every4Months")]
    Every4Months,
    #[serde(rename = "twiceAYear")]
    TwiceAYear,
    #[serde(rename = "yearly")]
    Yearly,
    #[serde(rename = "everyOtherYear")]
    EveryOtherYear,
}

impl Default for Frequency {
    fn default() -> Frequency {
        Self::Never
    }
}

