/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledSubTransaction {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "scheduled_transaction_id")]
    pub scheduled_transaction_id: String,
    /// The scheduled subtransaction amount in milliunits format
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "payee_id", skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<String>,
    #[serde(rename = "category_id", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<String>,
    /// If a transfer, the account_id which the scheduled subtransaction transfers to
    #[serde(rename = "transfer_account_id", skip_serializing_if = "Option::is_none")]
    pub transfer_account_id: Option<String>,
    /// Whether or not the scheduled subtransaction has been deleted.  Deleted scheduled subtransactions will only be included in delta requests.
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl ScheduledSubTransaction {
    pub fn new(id: String, scheduled_transaction_id: String, amount: i64, deleted: bool) -> ScheduledSubTransaction {
        ScheduledSubTransaction {
            id,
            scheduled_transaction_id,
            amount,
            memo: None,
            payee_id: None,
            category_id: None,
            transfer_account_id: None,
            deleted,
        }
    }
}


