/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.72.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubTransaction {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    /// The subtransaction amount in milliunits format
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "memo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memo: Option<Option<String>>,
    #[serde(rename = "payee_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "payee_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payee_name: Option<Option<String>>,
    #[serde(rename = "category_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "category_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_name: Option<Option<String>>,
    /// If a transfer, the account_id which the subtransaction transfers to
    #[serde(rename = "transfer_account_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transfer_account_id: Option<Option<uuid::Uuid>>,
    /// If a transfer, the id of transaction on the other side of the transfer
    #[serde(rename = "transfer_transaction_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transfer_transaction_id: Option<Option<String>>,
    /// Whether or not the subtransaction has been deleted.  Deleted subtransactions will only be included in delta requests.
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl SubTransaction {
    pub fn new(id: String, transaction_id: String, amount: i64, deleted: bool) -> SubTransaction {
        SubTransaction {
            id,
            transaction_id,
            amount,
            memo: None,
            payee_id: None,
            payee_name: None,
            category_id: None,
            category_name: None,
            transfer_account_id: None,
            transfer_transaction_id: None,
            deleted,
        }
    }
}

