/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.72.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionClearedStatus : The cleared status of the transaction
/// The cleared status of the transaction
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionClearedStatus {
    #[serde(rename = "cleared")]
    Cleared,
    #[serde(rename = "uncleared")]
    Uncleared,
    #[serde(rename = "reconciled")]
    Reconciled,

}

impl std::fmt::Display for TransactionClearedStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cleared => write!(f, "cleared"),
            Self::Uncleared => write!(f, "uncleared"),
            Self::Reconciled => write!(f, "reconciled"),
        }
    }
}

impl Default for TransactionClearedStatus {
    fn default() -> TransactionClearedStatus {
        Self::Cleared
    }
}

